//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Framework {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Framework() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Framework", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不正确的简写 “{0}”.
        /// </summary>
        internal static string Bible_IncorrectAbbreviation {
            get {
                return ResourceManager.GetString("Bible_IncorrectAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一页.
        /// </summary>
        internal static string Control_DataTable_LanguageFirst {
            get {
                return ResourceManager.GetString("Control_DataTable_LanguageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一共_TOTAL_条记录，显示其中的_START_到_END_.
        /// </summary>
        internal static string Control_DataTable_LanguageInfo {
            get {
                return ResourceManager.GetString("Control_DataTable_LanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有可用的记录.
        /// </summary>
        internal static string Control_DataTable_LanguageInfoEmpty {
            get {
                return ResourceManager.GetString("Control_DataTable_LanguageInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （从_MAX_条记录中过滤）.
        /// </summary>
        internal static string Control_DataTable_LanguageInfoFiltered {
            get {
                return ResourceManager.GetString("Control_DataTable_LanguageInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最后一页.
        /// </summary>
        internal static string Control_DataTable_LanguageLast {
            get {
                return ResourceManager.GetString("Control_DataTable_LanguageLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每页显示_MENU_条记录.
        /// </summary>
        internal static string Control_DataTable_LanguageLengthMenu {
            get {
                return ResourceManager.GetString("Control_DataTable_LanguageLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后一页.
        /// </summary>
        internal static string Control_DataTable_LanguageNext {
            get {
                return ResourceManager.GetString("Control_DataTable_LanguageNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前一页.
        /// </summary>
        internal static string Control_DataTable_LanguagePrevious {
            get {
                return ResourceManager.GetString("Control_DataTable_LanguagePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找：.
        /// </summary>
        internal static string Control_DataTable_LanguageSearch {
            get {
                return ResourceManager.GetString("Control_DataTable_LanguageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抱歉，没有任何记录.
        /// </summary>
        internal static string Control_DataTable_LanguageZeroRecords {
            get {
                return ResourceManager.GetString("Control_DataTable_LanguageZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会介绍.
        /// </summary>
        internal static string HomeAbout_Title {
            get {
                return ResourceManager.GetString("HomeAbout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 书卷.
        /// </summary>
        internal static string HomeBible_Book {
            get {
                return ResourceManager.GetString("HomeBible_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 章节.
        /// </summary>
        internal static string HomeBible_Chapter {
            get {
                return ResourceManager.GetString("HomeBible_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找... 例如，创1：1-31.
        /// </summary>
        internal static string HomeBible_SearchPlaceholder {
            get {
                return ResourceManager.GetString("HomeBible_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圣经.
        /// </summary>
        internal static string HomeBible_Title {
            get {
                return ResourceManager.GetString("HomeBible_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本.
        /// </summary>
        internal static string HomeBible_Version {
            get {
                return ResourceManager.GetString("HomeBible_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到这样的周报。.
        /// </summary>
        internal static string HomeBulletin_NoBulletinUploaded {
            get {
                return ResourceManager.GetString("HomeBulletin_NoBulletinUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主日周报.
        /// </summary>
        internal static string HomeBulletin_Title {
            get {
                return ResourceManager.GetString("HomeBulletin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        internal static string HomeIndex_Title {
            get {
                return ResourceManager.GetString("HomeIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图书馆.
        /// </summary>
        internal static string HomeLibrary_Title {
            get {
                return ResourceManager.GetString("HomeLibrary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期：.
        /// </summary>
        internal static string Home_Bulletin_Date {
            get {
                return ResourceManager.GetString("Home_Bulletin_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周报查询.
        /// </summary>
        internal static string Home_Bulletin_Legend {
            get {
                return ResourceManager.GetString("Home_Bulletin_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可打印版本.
        /// </summary>
        internal static string Home_Bulletin_PrintableVersion {
            get {
                return ResourceManager.GetString("Home_Bulletin_PrintableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        internal static string Home_Bulletin_Search {
            get {
                return ResourceManager.GetString("Home_Bulletin_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讲员：.
        /// </summary>
        internal static string Home_Bulletin_Speaker {
            get {
                return ResourceManager.GetString("Home_Bulletin_Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题目：《{0}》.
        /// </summary>
        internal static string Home_Bulletin_Title {
            get {
                return ResourceManager.GetString("Home_Bulletin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上载.
        /// </summary>
        internal static string Home_Bulletin_Upload {
            get {
                return ResourceManager.GetString("Home_Bulletin_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会资料.
        /// </summary>
        internal static string Home_Materials_Legend {
            get {
                return ResourceManager.GetString("Home_Materials_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        internal static string Home_Materials_TitleAuthor {
            get {
                return ResourceManager.GetString("Home_Materials_TitleAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期.
        /// </summary>
        internal static string Home_Materials_TitleDate {
            get {
                return ResourceManager.GetString("Home_Materials_TitleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题目.
        /// </summary>
        internal static string Home_Materials_TitleTitle {
            get {
                return ResourceManager.GetString("Home_Materials_TitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型.
        /// </summary>
        internal static string Home_Materials_TitleType {
            get {
                return ResourceManager.GetString("Home_Materials_TitleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 证道集锦.
        /// </summary>
        internal static string Home_Sermons_Legend {
            get {
                return ResourceManager.GetString("Home_Sermons_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期.
        /// </summary>
        internal static string Home_Sermons_TitleDate {
            get {
                return ResourceManager.GetString("Home_Sermons_TitleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讲员.
        /// </summary>
        internal static string Home_Sermons_TitleSpeaker {
            get {
                return ResourceManager.GetString("Home_Sermons_TitleSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题目.
        /// </summary>
        internal static string Home_Sermons_TitleTitle {
            get {
                return ResourceManager.GetString("Home_Sermons_TitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型.
        /// </summary>
        internal static string Home_Sermons_TitleType {
            get {
                return ResourceManager.GetString("Home_Sermons_TitleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当处理您的请求时出现一个错误。.
        /// </summary>
        internal static string SharedError_Content {
            get {
                return ResourceManager.GetString("SharedError_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误。.
        /// </summary>
        internal static string SharedError_Header {
            get {
                return ResourceManager.GetString("SharedError_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string SharedError_Title {
            get {
                return ResourceManager.GetString("SharedError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会介绍.
        /// </summary>
        internal static string Shared_Layout_About {
            get {
                return ResourceManager.GetString("Shared_Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 北维州华人浸信会.
        /// </summary>
        internal static string Shared_Layout_ApplicationName {
            get {
                return ResourceManager.GetString("Shared_Layout_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圣经.
        /// </summary>
        internal static string Shared_Layout_Bible {
            get {
                return ResourceManager.GetString("Shared_Layout_Bible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主日周报.
        /// </summary>
        internal static string Shared_Layout_Bulletin {
            get {
                return ResourceManager.GetString("Shared_Layout_Bulletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0}　-　北维州华人浸信会　|　11094 Lee Highway, A103　|　Fairfax VA | 22030　|　703.451.0815.
        /// </summary>
        internal static string Shared_Layout_Footer_Format {
            get {
                return ResourceManager.GetString("Shared_Layout_Footer_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        internal static string Shared_Layout_Index {
            get {
                return ResourceManager.GetString("Shared_Layout_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图书馆.
        /// </summary>
        internal static string Shared_Layout_Library {
            get {
                return ResourceManager.GetString("Shared_Layout_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string Shared_LoginPartial_LogIn {
            get {
                return ResourceManager.GetString("Shared_LoginPartial_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注销.
        /// </summary>
        internal static string Shared_LoginPartial_LogOff {
            get {
                return ResourceManager.GetString("Shared_LoginPartial_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        internal static string Shared_LoginPartial_Register {
            get {
                return ResourceManager.GetString("Shared_LoginPartial_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 北维州华人浸信会 - {0}.
        /// </summary>
        internal static string SiteWide_Title_Format {
            get {
                return ResourceManager.GetString("SiteWide_Title_Format", resourceCulture);
            }
        }
    }
}
