//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Nvcbc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nvcbc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Nvcbc", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会团契.
        /// </summary>
        internal static string HomeAbout_ChurchFellowship {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchFellowship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 团契就是一种伙伴关系，是一个结构，更是生命，是彼此间处于相交的状态。在团契里，弟兄姐妹同有、同享、同心合意、同负一轭、互通有无，汲取生命的营养，看到生命的彰显。.
        /// </summary>
        internal static string HomeAbout_ChurchFellowshipContent {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchFellowshipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 团契（英语：fellowship或communion），即伙伴关系，源自《圣经》中的“相交”一词，意思为相互交往和建立关系，是指上帝与人之间的相交和基督徒之间相交的亲密关系。.
        /// </summary>
        internal static string HomeAbout_ChurchFellowshipDetails1 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchFellowshipDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 团契正式成立之前，教会弟兄姐妹每周相聚在查经班，与普通查经班不同的是团契生活除了查考圣经，更致力于生活分享，探讨心灵的成长，帮助每个人与上帝之间建立起亲密的关系。.
        /// </summary>
        internal static string HomeAbout_ChurchFellowshipDetails2 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchFellowshipDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在短短的三年中我们从最初的 青年团契（同心同行的前身）发展壮大成目前的七个团契，蒙恩团契，同心同行团契系列，青少年团契，还有常青团契；这一路上都看到神与我们同在。每一个参加团契的弟兄姐妹每周五聚集在一起，查经祷告，分享生活，互相帮助，共同汲取生命的灵粮。.
        /// </summary>
        internal static string HomeAbout_ChurchFellowshipDetails3 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchFellowshipDetails3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会团契.
        /// </summary>
        internal static string HomeAbout_ChurchFellowshipTitle {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchFellowshipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会历史.
        /// </summary>
        internal static string HomeAbout_ChurchHistory {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ［北维州华人浸信会］前身是美国浸信会的华语部（Northern Virginia Chinese Baptist Mission）。 开创之初是美国教会几位姊妹成立的祷告会，这个祷告会是专门为拯救华人而成立的祷告会。祷告会蒙神怜悯，终于在1992 年迎来了华语部敬拜！直到2005 年华语部正式独立为华语教会，并注册为［北维州华人浸信会］。2008 年2 月离开美国母会迁移到现在的Oak View Elementary School开始主日敬拜到至今。.
        /// </summary>
        internal static string HomeAbout_ChurchHistoryContent1 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchHistoryContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 因为本教会是领受〈以弗所书〉四章十一节至十二节的教会行政原则。所以由牧师培养普通信徒让会众自己管理教会的行政模式。我们的活动是向任何人都是敞开的。教会欢迎你参与教会各项活动。当然我们更盼望早日看到您服侍大家，服侍教会！.
        /// </summary>
        internal static string HomeAbout_ChurchHistoryContent2 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchHistoryContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会历史图标.
        /// </summary>
        internal static string HomeAbout_ChurchHistoryIcon {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchHistoryIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会宣教.
        /// </summary>
        internal static string HomeAbout_ChurchMission {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会宣教.
        /// </summary>
        internal static string HomeAbout_ChurchMissionaryTitle {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchMissionaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主耶穌从死里复活，他给了我们一个大使命：「所以你们要去，使万民作我的门徒，奉父子圣灵的名，给他们施洗。凡我所吩咐你们的，都教训他们遵守，我就常与你们同在，直到世界的末了」。.
        /// </summary>
        internal static string HomeAbout_ChurchMissionContent {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchMissionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宣教日记.
        /// </summary>
        internal static string HomeAbout_ChurchMissionDetails1 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchMissionDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新中....
        /// </summary>
        internal static string HomeAbout_ChurchMissionDetails2 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchMissionDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会服侍.
        /// </summary>
        internal static string HomeAbout_ChurchService {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会是基督的身体，而这身体的意义就是服侍。如何成为这样的教会，像耶穌基督身子一样的活著，甚至成为这身体的一部分，这就是服侍的真正挑战，这也是我们一直以来的功课…….
        /// </summary>
        internal static string HomeAbout_ChurchServiceContent {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchServiceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生命成长.
        /// </summary>
        internal static string HomeAbout_ChurchServiceDetails1 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchServiceDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一个生命从孕育，成长到最后出生的过程实在是件奇迹，有无穷无尽的奥秘藏在其全部过程当中。属灵的重生和成长，也同样是件奇迹，主耶稣把这属灵的重生比作刮风。“风”本身是看不见的，但看到树叶的摇动后，谁也不能否认风在吹。重生也是如此，我们不能完全理解属灵重生的全部过程，但我们通过观察重生的人在生活上的转变，可以知道他已经在属灵上重生了。换句话说就是接受神的新生命，接受永生。也可以称之为悔改，得救。总而言之，重生是一个人在基督里完全变成新人的奇迹，重生的人在圣灵的帮助下，会逐渐的结出仁爱、喜乐、和平、忍耐、恩慈、良善、信实、温柔、节制等圣灵的果子。.
        /// </summary>
        internal static string HomeAbout_ChurchServiceDetails2 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchServiceDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社会服侍.
        /// </summary>
        internal static string HomeAbout_ChurchServiceDetails3 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchServiceDetails3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参与社区侍奉一直是我们长期以来的异象，从探访老人院，参与儿童圣诞鞋盒事工，扶持学生团契到参与county的社会服务等一直看到神给我们的带领。我们也相信教会的福音工作不仅仅来自于教会内部，更多地是要走出去。.
        /// </summary>
        internal static string HomeAbout_ChurchServiceDetails4 {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchServiceDetails4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会服侍.
        /// </summary>
        internal static string HomeAbout_ChurchServicesTitle {
            get {
                return ResourceManager.GetString("HomeAbout_ChurchServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请点击这里了解更多。.
        /// </summary>
        internal static string HomeAbout_ClickHereForMore {
            get {
                return ResourceManager.GetString("HomeAbout_ClickHereForMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会消息.
        /// </summary>
        internal static string HomeBulletin_Announcements {
            get {
                return ResourceManager.GetString("HomeBulletin_Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 家庭崇拜.
        /// </summary>
        internal static string HomeBulletin_FamilyWorship {
            get {
                return ResourceManager.GetString("HomeBulletin_FamilyWorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 诗歌: 《&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;{0}&lt;/a&gt;》.
        /// </summary>
        internal static string HomeBulletin_FamilyWorship_PraiseSong {
            get {
                return ResourceManager.GetString("HomeBulletin_FamilyWorship_PraiseSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 经文：{0}.
        /// </summary>
        internal static string HomeBulletin_FamilyWorship_Verse {
            get {
                return ResourceManager.GetString("HomeBulletin_FamilyWorship_Verse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记忆经文.
        /// </summary>
        internal static string HomeBulletin_MemorizedVerses {
            get {
                return ResourceManager.GetString("HomeBulletin_MemorizedVerses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上周：{0}.
        /// </summary>
        internal static string HomeBulletin_MemorizedVerses_LastWeek {
            get {
                return ResourceManager.GetString("HomeBulletin_MemorizedVerses_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本周：{0}.
        /// </summary>
        internal static string HomeBulletin_MemorizedVerses_ThisWeek {
            get {
                return ResourceManager.GetString("HomeBulletin_MemorizedVerses_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颂主新歌.
        /// </summary>
        internal static string HomeBulletin_NewSongForPraisingLord {
            get {
                return ResourceManager.GetString("HomeBulletin_NewSongForPraisingLord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 感恩代祷.
        /// </summary>
        internal static string HomeBulletin_PrayRequests {
            get {
                return ResourceManager.GetString("HomeBulletin_PrayRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 证道大纲.
        /// </summary>
        internal static string HomeBulletin_SermonCompendium {
            get {
                return ResourceManager.GetString("HomeBulletin_SermonCompendium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主日事工.
        /// </summary>
        internal static string HomeBulletin_Services {
            get {
                return ResourceManager.GetString("HomeBulletin_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下周.
        /// </summary>
        internal static string HomeBulletin_ServicesNextWeek {
            get {
                return ResourceManager.GetString("HomeBulletin_ServicesNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本周.
        /// </summary>
        internal static string HomeBulletin_ServicesThisWeek {
            get {
                return ResourceManager.GetString("HomeBulletin_ServicesThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 牧者的话.
        /// </summary>
        internal static string HomeBulletin_WordFromPaster {
            get {
                return ResourceManager.GetString("HomeBulletin_WordFromPaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者：{0}.
        /// </summary>
        internal static string HomeBulletin_WordFromPaster_Author {
            get {
                return ResourceManager.GetString("HomeBulletin_WordFromPaster_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主日崇拜.
        /// </summary>
        internal static string HomeBulletin_Worship {
            get {
                return ResourceManager.GetString("HomeBulletin_Worship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}（{1}）.
        /// </summary>
        internal static string HomeBulletin_WorshipItem {
            get {
                return ResourceManager.GetString("HomeBulletin_WorshipItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讲员：{0}.
        /// </summary>
        internal static string HomeBulletin_WorshipSermonSpeaker {
            get {
                return ResourceManager.GetString("HomeBulletin_WorshipSermonSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题目：{0}.
        /// </summary>
        internal static string HomeBulletin_WorshipSermonTitle {
            get {
                return ResourceManager.GetString("HomeBulletin_WorshipSermonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 经文：{0}.
        /// </summary>
        internal static string HomeBulletin_WorshipSermonVerses {
            get {
                return ResourceManager.GetString("HomeBulletin_WorshipSermonVerses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彼岸关爱基金.
        /// </summary>
        internal static string HomeIndex_BeyondOutreachFoundation {
            get {
                return ResourceManager.GetString("HomeIndex_BeyondOutreachFoundation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会活动.
        /// </summary>
        internal static string HomeIndex_ChurchActivities {
            get {
                return ResourceManager.GetString("HomeIndex_ChurchActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地点.
        /// </summary>
        internal static string HomeIndex_ChurchActivitiesHeaderLocation {
            get {
                return ResourceManager.GetString("HomeIndex_ChurchActivitiesHeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string HomeIndex_ChurchActivitiesHeaderName {
            get {
                return ResourceManager.GetString("HomeIndex_ChurchActivitiesHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电话.
        /// </summary>
        internal static string HomeIndex_ChurchActivitiesHeaderPhone {
            get {
                return ResourceManager.GetString("HomeIndex_ChurchActivitiesHeaderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间.
        /// </summary>
        internal static string HomeIndex_ChurchActivitiesHeaderTime {
            get {
                return ResourceManager.GetString("HomeIndex_ChurchActivitiesHeaderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我们诚挚的欢迎您来参加以下的聚会：.
        /// </summary>
        internal static string HomeIndex_ChurchActivitiesTitle {
            get {
                return ResourceManager.GetString("HomeIndex_ChurchActivitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会新闻.
        /// </summary>
        internal static string HomeIndex_ChurchNews {
            get {
                return ResourceManager.GetString("HomeIndex_ChurchNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示证道大纲.
        /// </summary>
        internal static string HomeIndex_DisplaySermonCompendium {
            get {
                return ResourceManager.GetString("HomeIndex_DisplaySermonCompendium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐藏证道大纲.
        /// </summary>
        internal static string HomeIndex_HideSermonCompendium {
            get {
                return ResourceManager.GetString("HomeIndex_HideSermonCompendium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新证道.
        /// </summary>
        internal static string HomeIndex_LatestSermon {
            get {
                return ResourceManager.GetString("HomeIndex_LatestSermon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相关链接.
        /// </summary>
        internal static string HomeIndex_RelatedLinks {
            get {
                return ResourceManager.GetString("HomeIndex_RelatedLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讲员：{0}.
        /// </summary>
        internal static string HomeIndex_SermonSpeaker {
            get {
                return ResourceManager.GetString("HomeIndex_SermonSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间：{0}.
        /// </summary>
        internal static string HomeIndex_SermonTime {
            get {
                return ResourceManager.GetString("HomeIndex_SermonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题目：{0}.
        /// </summary>
        internal static string HomeIndex_SermonTitle {
            get {
                return ResourceManager.GetString("HomeIndex_SermonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 《{0}》.
        /// </summary>
        internal static string HomeIndex_SermonTitle_Format {
            get {
                return ResourceManager.GetString("HomeIndex_SermonTitle_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎你来到［北维州华人浸信会］！.
        /// </summary>
        internal static string HomeIndex_WelcomeWord {
            get {
                return ResourceManager.GetString("HomeIndex_WelcomeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我是［北维州华人浸信会］的金春叶牧师，很高兴您给我们带来了主内服侍的机会！为了方便您未来在教会中的生活，容许我介绍以一下［北维州华人浸信会］。.
        /// </summary>
        internal static string HomeIndex_WelcomeWordContent1 {
            get {
                return ResourceManager.GetString("HomeIndex_WelcomeWordContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我们教会是因着耶稣基督的恩典来到一起相聚的团契。我们的宗旨是珍惜已经得到的恩典，并且不断追求在上帝里面更丰富的人生。我们祈盼恩典不仅能够存留在我们的生活当中，更渴望恩典能够广传，传播到同样需要恩典的生命！为的是让更多的生命蒙受神的恩典，让恩典传播的更多更远！这是我们［北维州华人浸信会］众弟兄姊妹的异象，也是北维州华人浸信会的生活与活动（虽然我们还不够完全）。.
        /// </summary>
        internal static string HomeIndex_WelcomeWordContent2 {
            get {
                return ResourceManager.GetString("HomeIndex_WelcomeWordContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我们欢欣在基督里认识您，并且服侍您！真诚希望您早日共享我们的异象和生活，并参与在我们的活动当中。这也是我们在上帝面前的祈求愿上帝赐福您和您的亲人平安喜乐！.
        /// </summary>
        internal static string HomeIndex_WelcomeWordContent3 {
            get {
                return ResourceManager.GetString("HomeIndex_WelcomeWordContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金春叶 牧师.
        /// </summary>
        internal static string HomeIndex_WelcomeWordContent4 {
            get {
                return ResourceManager.GetString("HomeIndex_WelcomeWordContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教会敬拜.
        /// </summary>
        internal static string HomeIndex_Worship {
            get {
                return ResourceManager.GetString("HomeIndex_Worship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主日早晨的崇拜是教会一周聚会的最主要崇拜聚会，若不是首先前来敬拜上帝，人是不配来事奉上帝的。崇拜就是人们首要的职责。当我们崇拜时，我们尊敬上帝，将上帝的荣耀归予祂，我们赞美祂、敬拜祂。我们将自己以及我们的礼物献给祂，因为祂是当得我们敬拜、赞美的神。.
        /// </summary>
        internal static string HomeIndex_WorshipContent {
            get {
                return ResourceManager.GetString("HomeIndex_WorshipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敬拜时间： 每周日上午10:00am到1:00pm.
        /// </summary>
        internal static string HomeIndex_WorshipContent2 {
            get {
                return ResourceManager.GetString("HomeIndex_WorshipContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敬拜地点：『5035 Sideburn Rd, Fairfax, VA 22032』.
        /// </summary>
        internal static string HomeIndex_WorshipContent3 {
            get {
                return ResourceManager.GetString("HomeIndex_WorshipContent3", resourceCulture);
            }
        }
    }
}
