//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 4/2/2017 4:17:17 PM
namespace Church.Models
{
    /// <summary>
    /// There are no comments for BulletinSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BulletinSingle")]
    public partial class BulletinSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Bulletin>
    {
        /// <summary>
        /// Initialize a new BulletinSingle object.
        /// </summary>
        public BulletinSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new BulletinSingle object.
        /// </summary>
        public BulletinSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new BulletinSingle object.
        /// </summary>
        public BulletinSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Bulletin> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Bulletin in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Bulletin")]
    public partial class Bulletin : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Bulletin object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Bulletin CreateBulletin(global::System.Guid ID)
        {
            Bulletin bulletin = new Bulletin();
            bulletin.Id = ID;
            return bulletin;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("date")]
        public global::System.Nullable<global::System.DateTimeOffset> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property FileUri in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("fileUri")]
        public string FileUri
        {
            get
            {
                return this._FileUri;
            }
            set
            {
                this.OnFileUriChanging(value);
                this._FileUri = value;
                this.OnFileUriChanged();
                this.OnPropertyChanged("fileUri");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FileUri;
        partial void OnFileUriChanging(string value);
        partial void OnFileUriChanged();
        /// <summary>
        /// There are no comments for Property Culture in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("culture")]
        public string Culture
        {
            get
            {
                return this._Culture;
            }
            set
            {
                this.OnCultureChanging(value);
                this._Culture = value;
                this.OnCultureChanged();
                this.OnPropertyChanged("culture");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Culture;
        partial void OnCultureChanging(string value);
        partial void OnCultureChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SermonSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SermonSingle")]
    public partial class SermonSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Sermon>
    {
        /// <summary>
        /// Initialize a new SermonSingle object.
        /// </summary>
        public SermonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SermonSingle object.
        /// </summary>
        public SermonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new SermonSingle object.
        /// </summary>
        public SermonSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Sermon> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Sermon in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Sermon")]
    public partial class Sermon : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Sermon object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Sermon CreateSermon(global::System.Guid ID)
        {
            Sermon sermon = new Sermon();
            sermon.Id = ID;
            return sermon;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("type")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("date")]
        public global::System.Nullable<global::System.DateTimeOffset> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Speaker in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("speaker")]
        public string Speaker
        {
            get
            {
                return this._Speaker;
            }
            set
            {
                this.OnSpeakerChanging(value);
                this._Speaker = value;
                this.OnSpeakerChanged();
                this.OnPropertyChanged("speaker");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Speaker;
        partial void OnSpeakerChanging(string value);
        partial void OnSpeakerChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("title")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property FileUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("fileUrl")]
        public string FileUrl
        {
            get
            {
                return this._FileUrl;
            }
            set
            {
                this.OnFileUrlChanging(value);
                this._FileUrl = value;
                this.OnFileUrlChanged();
                this.OnPropertyChanged("fileUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FileUrl;
        partial void OnFileUrlChanging(string value);
        partial void OnFileUrlChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MaterialSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MaterialSingle")]
    public partial class MaterialSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Material>
    {
        /// <summary>
        /// Initialize a new MaterialSingle object.
        /// </summary>
        public MaterialSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MaterialSingle object.
        /// </summary>
        public MaterialSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MaterialSingle object.
        /// </summary>
        public MaterialSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Material> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Material in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Material")]
    public partial class Material : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Material object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Material CreateMaterial(global::System.Guid ID)
        {
            Material material = new Material();
            material.Id = ID;
            return material;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("type")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("date")]
        public global::System.Nullable<global::System.DateTimeOffset> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Authors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("authors")]
        public string Authors
        {
            get
            {
                return this._Authors;
            }
            set
            {
                this.OnAuthorsChanging(value);
                this._Authors = value;
                this.OnAuthorsChanged();
                this.OnPropertyChanged("authors");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Authors;
        partial void OnAuthorsChanging(string value);
        partial void OnAuthorsChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("title")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property FileUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("fileUrl")]
        public string FileUrl
        {
            get
            {
                return this._FileUrl;
            }
            set
            {
                this.OnFileUrlChanging(value);
                this._FileUrl = value;
                this.OnFileUrlChanged();
                this.OnPropertyChanged("fileUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FileUrl;
        partial void OnFileUrlChanging(string value);
        partial void OnFileUrlChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for HymnSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("HymnSingle")]
    public partial class HymnSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Hymn>
    {
        /// <summary>
        /// Initialize a new HymnSingle object.
        /// </summary>
        public HymnSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new HymnSingle object.
        /// </summary>
        public HymnSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new HymnSingle object.
        /// </summary>
        public HymnSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Hymn> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Hymn in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Hymn")]
    public partial class Hymn : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Hymn object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Hymn CreateHymn(global::System.Guid ID)
        {
            Hymn hymn = new Hymn();
            hymn.Id = ID;
            return hymn;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Source in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("source")]
        public string Source
        {
            get
            {
                return this._Source;
            }
            set
            {
                this.OnSourceChanging(value);
                this._Source = value;
                this.OnSourceChanged();
                this.OnPropertyChanged("source");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Source;
        partial void OnSourceChanging(string value);
        partial void OnSourceChanged();
        /// <summary>
        /// There are no comments for Property Lyrics in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("lyrics")]
        public string Lyrics
        {
            get
            {
                return this._Lyrics;
            }
            set
            {
                this.OnLyricsChanging(value);
                this._Lyrics = value;
                this.OnLyricsChanged();
                this.OnPropertyChanged("lyrics");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Lyrics;
        partial void OnLyricsChanging(string value);
        partial void OnLyricsChanged();
        /// <summary>
        /// There are no comments for Property Links in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("links")]
        public string Links
        {
            get
            {
                return this._Links;
            }
            set
            {
                this.OnLinksChanging(value);
                this._Links = value;
                this.OnLinksChanged();
                this.OnPropertyChanged("links");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Links;
        partial void OnLinksChanging(string value);
        partial void OnLinksChanged();
        /// <summary>
        /// There are no comments for Property Culture in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("culture")]
        public string Culture
        {
            get
            {
                return this._Culture;
            }
            set
            {
                this.OnCultureChanging(value);
                this._Culture = value;
                this.OnCultureChanged();
                this.OnPropertyChanged("culture");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Culture;
        partial void OnCultureChanging(string value);
        partial void OnCultureChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Church.Models.Bulletin as global::Church.Models.BulletinSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Church.Models.BulletinSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Bulletin> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Church.Models.BulletinSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Church.Models.Bulletin as global::Church.Models.BulletinSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Church.Models.BulletinSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Bulletin> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "id", id }
            };
            return new global::Church.Models.BulletinSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Church.Models.Sermon as global::Church.Models.SermonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Church.Models.SermonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Sermon> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Church.Models.SermonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Church.Models.Sermon as global::Church.Models.SermonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Church.Models.SermonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Sermon> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "id", id }
            };
            return new global::Church.Models.SermonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Church.Models.Material as global::Church.Models.MaterialSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Church.Models.MaterialSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Material> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Church.Models.MaterialSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Church.Models.Material as global::Church.Models.MaterialSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Church.Models.MaterialSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Material> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "id", id }
            };
            return new global::Church.Models.MaterialSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Church.Models.Hymn as global::Church.Models.HymnSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Church.Models.HymnSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Hymn> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Church.Models.HymnSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Church.Models.Hymn as global::Church.Models.HymnSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Church.Models.HymnSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Hymn> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "id", id }
            };
            return new global::Church.Models.HymnSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Church.Website
{
    /// <summary>
    /// There are no comments for ODataService in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ODataService")]
    public partial class ODataService : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ODataService object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public ODataService(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Church.Website", "Church.Website");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Church.Models", "Church.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Church.Website", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Church.Website.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Church.Website.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Church.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Church.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Church.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Bulletins in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Bulletins")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Bulletin> Bulletins
        {
            get
            {
                if ((this._Bulletins == null))
                {
                    this._Bulletins = base.CreateQuery<global::Church.Models.Bulletin>("Bulletins");
                }
                return this._Bulletins;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Bulletin> _Bulletins;
        /// <summary>
        /// There are no comments for Sermons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Sermons")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Sermon> Sermons
        {
            get
            {
                if ((this._Sermons == null))
                {
                    this._Sermons = base.CreateQuery<global::Church.Models.Sermon>("Sermons");
                }
                return this._Sermons;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Sermon> _Sermons;
        /// <summary>
        /// There are no comments for Materials in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Materials")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Material> Materials
        {
            get
            {
                if ((this._Materials == null))
                {
                    this._Materials = base.CreateQuery<global::Church.Models.Material>("Materials");
                }
                return this._Materials;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Material> _Materials;
        /// <summary>
        /// There are no comments for Hymns in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Hymns")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Hymn> Hymns
        {
            get
            {
                if ((this._Hymns == null))
                {
                    this._Hymns = base.CreateQuery<global::Church.Models.Hymn>("Hymns");
                }
                return this._Hymns;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Church.Models.Hymn> _Hymns;
        /// <summary>
        /// There are no comments for Bulletins in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToBulletins(global::Church.Models.Bulletin bulletin)
        {
            base.AddObject("Bulletins", bulletin);
        }
        /// <summary>
        /// There are no comments for Sermons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToSermons(global::Church.Models.Sermon sermon)
        {
            base.AddObject("Sermons", sermon);
        }
        /// <summary>
        /// There are no comments for Materials in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToMaterials(global::Church.Models.Material material)
        {
            base.AddObject("Materials", material);
        }
        /// <summary>
        /// There are no comments for Hymns in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToHymns(global::Church.Models.Hymn hymn)
        {
            base.AddObject("Hymns", hymn);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Church.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Bulletin"" OpenType=""true"">
        <Key>
          <PropertyRef Name=""id"" />
        </Key>
        <Property Name=""id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""date"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""fileUri"" Type=""Edm.String"" />
        <Property Name=""culture"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""Sermon"">
        <Key>
          <PropertyRef Name=""id"" />
        </Key>
        <Property Name=""id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""type"" Type=""Edm.String"" />
        <Property Name=""date"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""speaker"" Type=""Edm.String"" />
        <Property Name=""title"" Type=""Edm.String"" />
        <Property Name=""fileUrl"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""Material"">
        <Key>
          <PropertyRef Name=""id"" />
        </Key>
        <Property Name=""id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""type"" Type=""Edm.String"" />
        <Property Name=""date"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""authors"" Type=""Edm.String"" />
        <Property Name=""title"" Type=""Edm.String"" />
        <Property Name=""fileUrl"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""Hymn"">
        <Key>
          <PropertyRef Name=""id"" />
        </Key>
        <Property Name=""id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""name"" Type=""Edm.String"" />
        <Property Name=""source"" Type=""Edm.String"" />
        <Property Name=""lyrics"" Type=""Edm.String"" />
        <Property Name=""links"" Type=""Edm.String"" />
        <Property Name=""culture"" Type=""Edm.String"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Church.Website"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""ODataService"">
        <EntitySet Name=""Bulletins"" EntityType=""Church.Models.Bulletin"" />
        <EntitySet Name=""Sermons"" EntityType=""Church.Models.Sermon"" />
        <EntitySet Name=""Materials"" EntityType=""Church.Models.Material"" />
        <EntitySet Name=""Hymns"" EntityType=""Church.Models.Hymn"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
