//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibleBook
    {
        public BibleBook()
        {
            this.BibleChapters = new HashSet<BibleChapter>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid BibleId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public int Order { get; set; }
    
        public virtual Bible Bible { get; set; }
        public virtual ICollection<BibleChapter> BibleChapters { get; set; }
    }
}
