//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hymn
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Source { get; set; }
        public string Lyrics { get; set; }
        public string Links { get; set; }
        public string Culture { get; set; }
    }
}
