//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models.EntityFramework
{
    using System.Collections.Generic;
    
    public partial class Bible
    {
        public Bible()
        {
            this.BibleBooks = new HashSet<BibleBook>();
        }
    
        public System.Guid Id { get; set; }
        public string Version { get; set; }
        public string Culture { get; set; }
        public string Language { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ICollection<BibleBook> BibleBooks { get; set; }
    }
}
